FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["MockBankingAPI.csproj", "./"]
RUN dotnet restore "MockBankingAPI.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "MockBankingAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MockBankingAPI.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MockBankingAPI.dll"]
